; generated by qd0c from _data/fact.qd
source_filename = "_data/fact.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [7 x i8] c"result\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.9 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.11 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.12 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.13 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.14 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.15 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.18 = private unnamed_addr constant [4 x i8] c"t16\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"t17\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t18\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.22 = private unnamed_addr constant [5 x i8] c"PASS\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"t19\00"
@.str.24 = private unnamed_addr constant [4 x i8] c"t20\00"
@.str.25 = private unnamed_addr constant [4 x i8] c"t21\00"
@.str.26 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.27 = private unnamed_addr constant [5 x i8] c"FAIL\00"
@.str.28 = private unnamed_addr constant [4 x i8] c"t22\00"
@.str.29 = private unnamed_addr constant [4 x i8] c"t23\00"
@.str.30 = private unnamed_addr constant [4 x i8] c"t24\00"

define i32 @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %result_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*
  %t17_slot = alloca %QdObj*
  %t18_slot = alloca %QdObj*
  %L_0_slot = alloca %QdObj*
  %t19_slot = alloca %QdObj*
  %t20_slot = alloca %QdObj*
  %t21_slot = alloca %QdObj*
  %t22_slot = alloca %QdObj*
  %t23_slot = alloca %QdObj*
  %t24_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %result_slot
  %_cs2 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_cs3 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  %_ln4 = call %QdObj* @qd_env_get(i8* %_cs3)
  store %QdObj* %_ln4, %QdObj** %t1_slot
  %_v5 = call %QdObj* @qd_int(i64 2)
  store %QdObj* %_v5, %QdObj** %t2_slot
  %_v6 = load %QdObj*, %QdObj** %t1_slot
  %_v7 = load %QdObj*, %QdObj** %t2_slot
  %_ar8 = call %QdObj* @qd_mul(%QdObj* %_v6, %QdObj* %_v7)
  store %QdObj* %_ar8, %QdObj** %t3_slot
  %_v9 = load %QdObj*, %QdObj** %t3_slot
  store %QdObj* %_v9, %QdObj** %result_slot
  %_cs10 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs10, %QdObj* %_v9)
  %_cs11 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  %_ln12 = call %QdObj* @qd_env_get(i8* %_cs11)
  store %QdObj* %_ln12, %QdObj** %t4_slot
  %_v13 = call %QdObj* @qd_int(i64 3)
  store %QdObj* %_v13, %QdObj** %t5_slot
  %_v14 = load %QdObj*, %QdObj** %t4_slot
  %_v15 = load %QdObj*, %QdObj** %t5_slot
  %_ar16 = call %QdObj* @qd_mul(%QdObj* %_v14, %QdObj* %_v15)
  store %QdObj* %_ar16, %QdObj** %t6_slot
  %_v17 = load %QdObj*, %QdObj** %t6_slot
  store %QdObj* %_v17, %QdObj** %result_slot
  %_cs18 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs18, %QdObj* %_v17)
  %_cs19 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  %_ln20 = call %QdObj* @qd_env_get(i8* %_cs19)
  store %QdObj* %_ln20, %QdObj** %t7_slot
  %_v21 = call %QdObj* @qd_int(i64 4)
  store %QdObj* %_v21, %QdObj** %t8_slot
  %_v22 = load %QdObj*, %QdObj** %t7_slot
  %_v23 = load %QdObj*, %QdObj** %t8_slot
  %_ar24 = call %QdObj* @qd_mul(%QdObj* %_v22, %QdObj* %_v23)
  store %QdObj* %_ar24, %QdObj** %t9_slot
  %_v25 = load %QdObj*, %QdObj** %t9_slot
  store %QdObj* %_v25, %QdObj** %result_slot
  %_cs26 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs26, %QdObj* %_v25)
  %_cs27 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  %_ln28 = call %QdObj* @qd_env_get(i8* %_cs27)
  store %QdObj* %_ln28, %QdObj** %t10_slot
  %_v29 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v29, %QdObj** %t11_slot
  %_v30 = load %QdObj*, %QdObj** %t10_slot
  %_v31 = load %QdObj*, %QdObj** %t11_slot
  %_ar32 = call %QdObj* @qd_mul(%QdObj* %_v30, %QdObj* %_v31)
  store %QdObj* %_ar32, %QdObj** %t12_slot
  %_v33 = load %QdObj*, %QdObj** %t12_slot
  store %QdObj* %_v33, %QdObj** %result_slot
  %_cs34 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs34, %QdObj* %_v33)
  %_cs35 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  %_ln36 = call %QdObj* @qd_env_get(i8* %_cs35)
  store %QdObj* %_ln36, %QdObj** %t13_slot
  %_v37 = load %QdObj*, %QdObj** %t13_slot
  %_cs38 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.15, i32 0, i32 0
  %_ln39 = call %QdObj* @qd_env_get(i8* %_cs38)
  store %QdObj* %_ln39, %QdObj** %t14_slot
  %_v40 = load %QdObj*, %QdObj** %t14_slot
  %_argv41 = alloca %QdObj*, i32 1
  %_ap42 = getelementptr %QdObj*, %QdObj** %_argv41, i32 0
  store %QdObj* %_v37, %QdObj** %_ap42
  %_cr43 = call %QdObj* @qd_call(%QdObj* %_v40, %QdObj** %_argv41, i32 1)
  store %QdObj* %_cr43, %QdObj** %t15_slot
  %_cs44 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.1, i32 0, i32 0
  %_ln45 = call %QdObj* @qd_env_get(i8* %_cs44)
  store %QdObj* %_ln45, %QdObj** %t16_slot
  %_v46 = call %QdObj* @qd_int(i64 120)
  store %QdObj* %_v46, %QdObj** %t17_slot
  %_v47 = load %QdObj*, %QdObj** %t16_slot
  %_v48 = load %QdObj*, %QdObj** %t17_slot
  %_cm49 = call %QdObj* @qd_cmp_eq(%QdObj* %_v47, %QdObj* %_v48)
  store %QdObj* %_cm49, %QdObj** %t18_slot
  %_v50 = load %QdObj*, %QdObj** %t18_slot
  %_bt51 = call i32 @qd_truthy(%QdObj* %_v50)
  %_bc52 = icmp ne i32 %_bt51, 0
  br i1 %_bc52, label %_fall53, label %L_0

_fall53:
  %_gp55 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.22, i32 0, i32 0
  %_v54 = call %QdObj* @qd_string(i8* %_gp55)
  store %QdObj* %_v54, %QdObj** %t19_slot
  %_v56 = load %QdObj*, %QdObj** %t19_slot
  %_cs57 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.15, i32 0, i32 0
  %_ln58 = call %QdObj* @qd_env_get(i8* %_cs57)
  store %QdObj* %_ln58, %QdObj** %t20_slot
  %_v59 = load %QdObj*, %QdObj** %t20_slot
  %_argv60 = alloca %QdObj*, i32 1
  %_ap61 = getelementptr %QdObj*, %QdObj** %_argv60, i32 0
  store %QdObj* %_v56, %QdObj** %_ap61
  %_cr62 = call %QdObj* @qd_call(%QdObj* %_v59, %QdObj** %_argv60, i32 1)
  store %QdObj* %_cr62, %QdObj** %t21_slot
  br label %L_1

L_0:
  %_gp64 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.27, i32 0, i32 0
  %_v63 = call %QdObj* @qd_string(i8* %_gp64)
  store %QdObj* %_v63, %QdObj** %t22_slot
  %_v65 = load %QdObj*, %QdObj** %t22_slot
  %_cs66 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.15, i32 0, i32 0
  %_ln67 = call %QdObj* @qd_env_get(i8* %_cs66)
  store %QdObj* %_ln67, %QdObj** %t23_slot
  %_v68 = load %QdObj*, %QdObj** %t23_slot
  %_argv69 = alloca %QdObj*, i32 1
  %_ap70 = getelementptr %QdObj*, %QdObj** %_argv69, i32 0
  store %QdObj* %_v65, %QdObj** %_ap70
  %_cr71 = call %QdObj* @qd_call(%QdObj* %_v68, %QdObj** %_argv69, i32 1)
  store %QdObj* %_cr71, %QdObj** %t24_slot
  br label %L_1

L_1:

  ret i32 0
}
