; generated by qd0c from _data/fact_recursive.qd
source_filename = "_data/fact_recursive.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [10 x i8] c"factorial\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"n\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"L_0\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t7\00"
@.str.11 = private unnamed_addr constant [4 x i8] c"L_1\00"
@.str.12 = private unnamed_addr constant [3 x i8] c"t8\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"t9\00"
@.str.14 = private unnamed_addr constant [4 x i8] c"t10\00"
@.str.15 = private unnamed_addr constant [4 x i8] c"t11\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"t12\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"t13\00"
@.str.18 = private unnamed_addr constant [4 x i8] c"t14\00"
@.str.19 = private unnamed_addr constant [4 x i8] c"t15\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"t16\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"t17\00"
@.str.22 = private unnamed_addr constant [7 x i8] c"result\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"t18\00"
@.str.24 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.25 = private unnamed_addr constant [4 x i8] c"t19\00"
@.str.26 = private unnamed_addr constant [4 x i8] c"t20\00"
@.str.27 = private unnamed_addr constant [4 x i8] c"t21\00"
@.str.28 = private unnamed_addr constant [4 x i8] c"t22\00"
@.str.29 = private unnamed_addr constant [4 x i8] c"t23\00"
@.str.30 = private unnamed_addr constant [4 x i8] c"L_2\00"
@.str.31 = private unnamed_addr constant [5 x i8] c"PASS\00"
@.str.32 = private unnamed_addr constant [4 x i8] c"t24\00"
@.str.33 = private unnamed_addr constant [4 x i8] c"t25\00"
@.str.34 = private unnamed_addr constant [4 x i8] c"t26\00"
@.str.35 = private unnamed_addr constant [4 x i8] c"L_3\00"
@.str.36 = private unnamed_addr constant [5 x i8] c"FAIL\00"
@.str.37 = private unnamed_addr constant [4 x i8] c"t27\00"
@.str.38 = private unnamed_addr constant [4 x i8] c"t28\00"
@.str.39 = private unnamed_addr constant [4 x i8] c"t29\00"

define %QdObj* @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %L_0_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*
  %t8_slot = alloca %QdObj*
  %t9_slot = alloca %QdObj*
  %t10_slot = alloca %QdObj*
  %t11_slot = alloca %QdObj*
  %t12_slot = alloca %QdObj*
  %t13_slot = alloca %QdObj*
  %t14_slot = alloca %QdObj*
  %t15_slot = alloca %QdObj*
  %t16_slot = alloca %QdObj*
  %t17_slot = alloca %QdObj*
  %result_slot = alloca %QdObj*
  %t18_slot = alloca %QdObj*
  %t19_slot = alloca %QdObj*
  %t20_slot = alloca %QdObj*
  %t21_slot = alloca %QdObj*
  %t22_slot = alloca %QdObj*
  %t23_slot = alloca %QdObj*
  %L_2_slot = alloca %QdObj*
  %t24_slot = alloca %QdObj*
  %t25_slot = alloca %QdObj*
  %t26_slot = alloca %QdObj*
  %t27_slot = alloca %QdObj*
  %t28_slot = alloca %QdObj*
  %t29_slot = alloca %QdObj*

  br label %factorial

factorial:
  %_cs0 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln1 = call %QdObj* @qd_env_get(i8* %_cs0)
  store %QdObj* %_ln1, %QdObj** %t0_slot
  %_v2 = call %QdObj* @qd_int(i64 0)
  store %QdObj* %_v2, %QdObj** %t1_slot
  %_v3 = load %QdObj*, %QdObj** %t0_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  %_cm5 = call %QdObj* @qd_cmp_eq(%QdObj* %_v3, %QdObj* %_v4)
  store %QdObj* %_cm5, %QdObj** %t2_slot
  %_cs6 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln7 = call %QdObj* @qd_env_get(i8* %_cs6)
  store %QdObj* %_ln7, %QdObj** %t3_slot
  %_v8 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v8, %QdObj** %t4_slot
  %_v9 = load %QdObj*, %QdObj** %t3_slot
  %_v10 = load %QdObj*, %QdObj** %t4_slot
  %_cm11 = call %QdObj* @qd_cmp_eq(%QdObj* %_v9, %QdObj* %_v10)
  store %QdObj* %_cm11, %QdObj** %t5_slot
  ; [TODO: BITOR t2 t5 t6]
  %_v12 = load %QdObj*, %QdObj** %t6_slot
  %_bt13 = call i32 @qd_truthy(%QdObj* %_v12)
  %_bc14 = icmp ne i32 %_bt13, 0
  br i1 %_bc14, label %_fall15, label %L_0

_fall15:
  %_v16 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v16, %QdObj** %t7_slot
  %_v17 = load %QdObj*, %QdObj** %t7_slot
  ret %QdObj* %_v17
  br label %L_1

L_0:
  br label %L_1

L_1:
  %_cs18 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln19 = call %QdObj* @qd_env_get(i8* %_cs18)
  store %QdObj* %_ln19, %QdObj** %t8_slot
  %_cs20 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln21 = call %QdObj* @qd_env_get(i8* %_cs20)
  store %QdObj* %_ln21, %QdObj** %t9_slot
  %_v22 = call %QdObj* @qd_int(i64 1)
  store %QdObj* %_v22, %QdObj** %t10_slot
  %_v23 = load %QdObj*, %QdObj** %t9_slot
  %_v24 = load %QdObj*, %QdObj** %t10_slot
  %_ar25 = call %QdObj* @qd_sub(%QdObj* %_v23, %QdObj* %_v24)
  store %QdObj* %_ar25, %QdObj** %t11_slot
  %_v26 = load %QdObj*, %QdObj** %t11_slot
  %_cs27 = getelementptr inbounds [10 x i8], [10 x i8]* @.str.0, i32 0, i32 0
  %_ln28 = call %QdObj* @qd_env_get(i8* %_cs27)
  store %QdObj* %_ln28, %QdObj** %t12_slot
  %_v29 = load %QdObj*, %QdObj** %t12_slot
  %_argv30 = alloca %QdObj*, i32 1
  %_ap31 = getelementptr %QdObj*, %QdObj** %_argv30, i32 0
  store %QdObj* %_v26, %QdObj** %_ap31
  %_cr32 = call %QdObj* @qd_call(%QdObj* %_v29, %QdObj** %_argv30, i32 1)
  store %QdObj* %_cr32, %QdObj** %t13_slot
  %_v33 = load %QdObj*, %QdObj** %t8_slot
  %_v34 = load %QdObj*, %QdObj** %t13_slot
  %_ar35 = call %QdObj* @qd_mul(%QdObj* %_v33, %QdObj* %_v34)
  store %QdObj* %_ar35, %QdObj** %t14_slot
  %_v36 = load %QdObj*, %QdObj** %t14_slot
  ret %QdObj* %_v36
  %_v37 = call %QdObj* @qd_int(i64 5)
  store %QdObj* %_v37, %QdObj** %t15_slot
  %_v38 = load %QdObj*, %QdObj** %t15_slot
  %_cs39 = getelementptr inbounds [10 x i8], [10 x i8]* @.str.0, i32 0, i32 0
  %_ln40 = call %QdObj* @qd_env_get(i8* %_cs39)
  store %QdObj* %_ln40, %QdObj** %t16_slot
  %_v41 = load %QdObj*, %QdObj** %t16_slot
  %_argv42 = alloca %QdObj*, i32 1
  %_ap43 = getelementptr %QdObj*, %QdObj** %_argv42, i32 0
  store %QdObj* %_v38, %QdObj** %_ap43
  %_cr44 = call %QdObj* @qd_call(%QdObj* %_v41, %QdObj** %_argv42, i32 1)
  store %QdObj* %_cr44, %QdObj** %t17_slot
  %_v45 = load %QdObj*, %QdObj** %t17_slot
  store %QdObj* %_v45, %QdObj** %result_slot
  %_cs46 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.22, i32 0, i32 0
  call void @qd_env_set(i8* %_cs46, %QdObj* %_v45)
  %_cs47 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.22, i32 0, i32 0
  %_ln48 = call %QdObj* @qd_env_get(i8* %_cs47)
  store %QdObj* %_ln48, %QdObj** %t18_slot
  %_v49 = load %QdObj*, %QdObj** %t18_slot
  %_cs50 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.24, i32 0, i32 0
  %_ln51 = call %QdObj* @qd_env_get(i8* %_cs50)
  store %QdObj* %_ln51, %QdObj** %t19_slot
  %_v52 = load %QdObj*, %QdObj** %t19_slot
  %_argv53 = alloca %QdObj*, i32 1
  %_ap54 = getelementptr %QdObj*, %QdObj** %_argv53, i32 0
  store %QdObj* %_v49, %QdObj** %_ap54
  %_cr55 = call %QdObj* @qd_call(%QdObj* %_v52, %QdObj** %_argv53, i32 1)
  store %QdObj* %_cr55, %QdObj** %t20_slot
  %_cs56 = getelementptr inbounds [7 x i8], [7 x i8]* @.str.22, i32 0, i32 0
  %_ln57 = call %QdObj* @qd_env_get(i8* %_cs56)
  store %QdObj* %_ln57, %QdObj** %t21_slot
  %_v58 = call %QdObj* @qd_int(i64 120)
  store %QdObj* %_v58, %QdObj** %t22_slot
  %_v59 = load %QdObj*, %QdObj** %t21_slot
  %_v60 = load %QdObj*, %QdObj** %t22_slot
  %_cm61 = call %QdObj* @qd_cmp_eq(%QdObj* %_v59, %QdObj* %_v60)
  store %QdObj* %_cm61, %QdObj** %t23_slot
  %_v62 = load %QdObj*, %QdObj** %t23_slot
  %_bt63 = call i32 @qd_truthy(%QdObj* %_v62)
  %_bc64 = icmp ne i32 %_bt63, 0
  br i1 %_bc64, label %_fall65, label %L_2

_fall65:
  %_gp67 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.31, i32 0, i32 0
  %_v66 = call %QdObj* @qd_string(i8* %_gp67)
  store %QdObj* %_v66, %QdObj** %t24_slot
  %_v68 = load %QdObj*, %QdObj** %t24_slot
  %_cs69 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.24, i32 0, i32 0
  %_ln70 = call %QdObj* @qd_env_get(i8* %_cs69)
  store %QdObj* %_ln70, %QdObj** %t25_slot
  %_v71 = load %QdObj*, %QdObj** %t25_slot
  %_argv72 = alloca %QdObj*, i32 1
  %_ap73 = getelementptr %QdObj*, %QdObj** %_argv72, i32 0
  store %QdObj* %_v68, %QdObj** %_ap73
  %_cr74 = call %QdObj* @qd_call(%QdObj* %_v71, %QdObj** %_argv72, i32 1)
  store %QdObj* %_cr74, %QdObj** %t26_slot
  br label %L_3

L_2:
  %_gp76 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.36, i32 0, i32 0
  %_v75 = call %QdObj* @qd_string(i8* %_gp76)
  store %QdObj* %_v75, %QdObj** %t27_slot
  %_v77 = load %QdObj*, %QdObj** %t27_slot
  %_cs78 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.24, i32 0, i32 0
  %_ln79 = call %QdObj* @qd_env_get(i8* %_cs78)
  store %QdObj* %_ln79, %QdObj** %t28_slot
  %_v80 = load %QdObj*, %QdObj** %t28_slot
  %_argv81 = alloca %QdObj*, i32 1
  %_ap82 = getelementptr %QdObj*, %QdObj** %_argv81, i32 0
  store %QdObj* %_v77, %QdObj** %_ap82
  %_cr83 = call %QdObj* @qd_call(%QdObj* %_v80, %QdObj** %_argv81, i32 1)
  store %QdObj* %_cr83, %QdObj** %t29_slot
  br label %L_3

L_3:

  ret %QdObj* zeroinitializer
}
