; generated by qd0c from _data/sub.qd
source_filename = "_data/sub.qd"

; ---- qd0lib 宣告 ----
%QdObj  = type opaque
%QdIter = type opaque

declare %QdObj*  @qd_none()
declare %QdObj*  @qd_bool(i32)
declare %QdObj*  @qd_int(i64)
declare %QdObj*  @qd_float(double)
declare %QdObj*  @qd_string(i8*)
declare %QdObj*  @qd_list_new()
declare %QdObj*  @qd_map_new()
declare %QdObj*  @qd_add(%QdObj*, %QdObj*)
declare %QdObj*  @qd_sub(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mul(%QdObj*, %QdObj*)
declare %QdObj*  @qd_div(%QdObj*, %QdObj*)
declare %QdObj*  @qd_floordiv(%QdObj*, %QdObj*)
declare %QdObj*  @qd_mod(%QdObj*, %QdObj*)
declare %QdObj*  @qd_pow(%QdObj*, %QdObj*)
declare %QdObj*  @qd_neg(%QdObj*)
declare %QdObj*  @qd_not(%QdObj*)
declare %QdObj*  @qd_cmp_eq(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ne(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_lt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_le(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_gt(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_ge(%QdObj*, %QdObj*)
declare %QdObj*  @qd_cmp_is(%QdObj*, %QdObj*)
declare %QdObj*  @qd_getattr(%QdObj*, i8*)
declare void      @qd_setattr(%QdObj*, i8*, %QdObj*)
declare %QdObj*  @qd_getitem(%QdObj*, %QdObj*)
declare void      @qd_setitem(%QdObj*, %QdObj*, %QdObj*)
declare void      @qd_list_append(%QdObj*, %QdObj*)
declare %QdIter* @qd_iter_new(%QdObj*)
declare %QdObj*  @qd_iter_next(%QdIter*)
declare i32       @qd_iter_done(%QdIter*)
declare %QdObj*  @qd_call(%QdObj*, %QdObj**, i32)
declare i32       @qd_truthy(%QdObj*)
declare void      @qd_print(%QdObj*)
declare void      @qd_env_init()
declare void      @qd_env_set(i8*, %QdObj*)
declare %QdObj*  @qd_env_get(i8*)
declare void      @exit(i32) noreturn

@.str.0 = private unnamed_addr constant [3 x i8] c"t0\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"x\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"t1\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"y\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"t2\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"t3\00"
@.str.6 = private unnamed_addr constant [3 x i8] c"t4\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"z\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"t5\00"
@.str.9 = private unnamed_addr constant [6 x i8] c"print\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"t6\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"t7\00"

define i32 @main() {
entry:
  call void @qd_env_init()

  %t0_slot = alloca %QdObj*
  %x_slot = alloca %QdObj*
  %t1_slot = alloca %QdObj*
  %y_slot = alloca %QdObj*
  %t2_slot = alloca %QdObj*
  %t3_slot = alloca %QdObj*
  %t4_slot = alloca %QdObj*
  %z_slot = alloca %QdObj*
  %t5_slot = alloca %QdObj*
  %t6_slot = alloca %QdObj*
  %t7_slot = alloca %QdObj*

  %_v0 = call %QdObj* @qd_int(i64 100)
  store %QdObj* %_v0, %QdObj** %t0_slot
  %_v1 = load %QdObj*, %QdObj** %t0_slot
  store %QdObj* %_v1, %QdObj** %x_slot
  %_cs2 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  call void @qd_env_set(i8* %_cs2, %QdObj* %_v1)
  %_v3 = call %QdObj* @qd_int(i64 50)
  store %QdObj* %_v3, %QdObj** %t1_slot
  %_v4 = load %QdObj*, %QdObj** %t1_slot
  store %QdObj* %_v4, %QdObj** %y_slot
  %_cs5 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  call void @qd_env_set(i8* %_cs5, %QdObj* %_v4)
  %_cs6 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i32 0, i32 0
  %_ln7 = call %QdObj* @qd_env_get(i8* %_cs6)
  store %QdObj* %_ln7, %QdObj** %t2_slot
  %_cs8 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.3, i32 0, i32 0
  %_ln9 = call %QdObj* @qd_env_get(i8* %_cs8)
  store %QdObj* %_ln9, %QdObj** %t3_slot
  %_v10 = load %QdObj*, %QdObj** %t2_slot
  %_v11 = load %QdObj*, %QdObj** %t3_slot
  %_ar12 = call %QdObj* @qd_sub(%QdObj* %_v10, %QdObj* %_v11)
  store %QdObj* %_ar12, %QdObj** %t4_slot
  %_v13 = load %QdObj*, %QdObj** %t4_slot
  store %QdObj* %_v13, %QdObj** %z_slot
  %_cs14 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.7, i32 0, i32 0
  call void @qd_env_set(i8* %_cs14, %QdObj* %_v13)
  %_cs15 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.7, i32 0, i32 0
  %_ln16 = call %QdObj* @qd_env_get(i8* %_cs15)
  store %QdObj* %_ln16, %QdObj** %t5_slot
  %_v17 = load %QdObj*, %QdObj** %t5_slot
  %_cs18 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.9, i32 0, i32 0
  %_ln19 = call %QdObj* @qd_env_get(i8* %_cs18)
  store %QdObj* %_ln19, %QdObj** %t6_slot
  %_v20 = load %QdObj*, %QdObj** %t6_slot
  %_argv21 = alloca %QdObj*, i32 1
  %_ap22 = getelementptr %QdObj*, %QdObj** %_argv21, i32 0
  store %QdObj* %_v17, %QdObj** %_ap22
  %_cr23 = call %QdObj* @qd_call(%QdObj* %_v20, %QdObj** %_argv21, i32 1)
  store %QdObj* %_cr23, %QdObj** %t7_slot

  ret i32 0
}
